### ISSUE TITLE
Investigate possibility to make `UniqueValuesSelector` searchable.

### ISSUE THREAD

**Issue by saskliutas** [iTwin/presentation#441]

**Comment by grigasp** [comment]
Looked into filtering distinct values on the backend and I think there's no big difference on whether we do that there, or on the frontend. 

We get distinct values on the backend by requesting raw values, formatting them, and grouping by formatted value. That means we can't use user's input as a query parameter, because formatted value may be completely different from the raw value that's stored in the iModel. So we would have to match against user's input **after** the formatting step, at which point there's not that much difference compared to filtering on the frontend. The downside is that response has to include values that we're going to drop (downloading them unnecessarily), but the upside is that it doesn't change the RPC / public API, so we don't have to bump peer dependencies or apply any hacks in our components.

Based on the above, I'd say we should filter the values in the component.
