### ISSUE TITLE
Investigate why base class grouping is so slow

### ISSUE THREAD

**Issue by grigasp** [iTwin/presentation#480]
Performance benchmark shows that base class grouping is twice as slow as other grouping types:

| Benchmark suite | Current: b6162e1199d4ef4385a1f5b2da52e323128bd1a5 | 
|-|-|
| `grouping by label` | `8416.82` ms | 
| `grouping by label (P95 of main thread blocks)` | `0` ms | 
| `grouping by class` | `8576.47` ms | 
| `grouping by class (P95 of main thread blocks)` | `0` ms | 
| `grouping by property` | `9114.43` ms | 
| `grouping by property (P95 of main thread blocks)` | `447` ms | 
| **`grouping by base class (10 classes)`** | **`23407.32` ms** | 
| **`grouping by base class (10 classes) (P95 of main thread blocks)`** | **`5948` ms** | 

Need to investigate why it's much slower and why the main thread is getting blocked so much.

**Comment by Yato333** [comment]
Grouping by base class is incredibly slow due to the fact that node cache is too small. When we request for children of grouping nodes of child class 2, node cache overfills and the entire hierarchy has to be recreated. This can be proved by setting `HierarchyProviderProps.queryCacheSize` to `Number.MAX_SAFE_INTEGER` and seeing that it fixes the problem.
